import './globals.css'

export const metadata = {
  title: 'Hacker Code',
  description: 'Generated by Ihar Anikeyenka',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
